### ISSUE TITLE
How to change application port

### ISSUE THREAD

**Issue by brylie** [ebsuku/python3-qoqa#2]
Is it still advisable to run quqa apps behind a reverse proxy, or can we change the port number (e.g. to 80 or 443)?

**Comment by knightebsuku** [comment]
The port number can be changed in the project.service file.
For my very small django applications, I serve the application directly via gunicorn. whitenoise will then handle the static files

For large application a reverse proxy is a good idea

**Comment by brylie** [comment]
Cool beans. Yeah, serving on port 443 (with a redirect from requests to port 80) would be a common pattern to support.
