### ISSUE TITLE
Support building for python 3.5 

### ISSUE THREAD

**Issue by knightebsuku** [ebsuku/python3-qoqa#6]
From @zek 

I cannot run the generated application in different environments.

installed library path is
/opt/venvs/fruit/lib/python3.6

but I'm trying to run it on python3.5 so python searches libraries in
/opt/venvs/fruit/lib/python3.5

Is it possible something like
/opt/venvs/fruit/lib/python3

**Comment by knightebsuku** [comment]
I've also come across this problem and not really sure how to correct it.

I think the main issue is that you cant create a virtualenv for a general python version, it has to be specific

One idea is to check which python version is running on the host machine then create the appropriate symbolic links in the env directory. 

I'll need to dig deeper into debian packaging, perhaps they will be something there.

**Comment by zek** [comment]
OK I found a solution for it.

we should move libraries into lib/python3/dist-packages 
~~~
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/opt/venvs/panlogs/lib/python3/dist-packages']
~~~

It doesnt see packages which is located in site-packages folder.

**Comment by zek** [comment]
Also we may use distribute option maybe ( https://virtualenv.pypa.io/en/stable/reference/#cmdoption-distribute ) It may solve our version problem. I didn't try it. Not sure if it is what we are looking for. But moving folders like I said is looks the best solution for now

**Comment by knightebsuku** [comment]
Fixed
