### ISSUE TITLE
Building Directory

### ISSUE THREAD

**Issue by zek** [ebsuku/python3-qoqa#7]
Is it possible to build files (like .deb files) into a build/ folder in the main directory? Or in a folder like release.

**Comment by knightebsuku** [comment]
I don't think so. You'd need to write something outside of dpkg-buildpackage to move that file.

What is your use case?

**Comment by zek** [comment]
Building creates so many files in parent directory. I prefer organising
files. Everytime when I build, I am moving and deleting files from parent
directory and there are some other files. This is so confusing.
27 Tem 2018 Cum, saat 16:29 tarihinde Lunga Mthembu <
notifications@github.com> şunu yazdı:

**Comment by knightebsuku** [comment]
That's true, I just wrote a small script that does that for me
